name: File Content Action
description: Retrieve content of a file in a pull request
author: Sidharth Bhardwaj

inputs:

  file_path:
    description: 'The path of the file to retrieve'
    required: true
  pr_number:
    description: 'The number of the pull request'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  # personal_token: 'The token use to access octokit and comment in issues'
  #   required: true
  api_key: 
    description: 'CVE API KEY'
    required: true
  api_user: 
    description: 'CVE API username'
    required: true
  api_org: 
    description: 'CVE API organization'
    required: true

outputs:

  file_content:
    description: 'The content of the file'

runs:
  using: 'node16'
  main: 'dist/index.js'
