name: learn-github-actions
on: [push]
jobs:
  Printing-Hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16'
      - run: echo "Hello, thanks for contribution"