name: learn-github-actions
on: 
  pull_request:
    types: [opened, reopened]
    
jobs:
  Printing-Hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, thanks for contribution"

  Taking-pull-request-file:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Retrieve file content
        id: retrieve-file
        uses: ./ 
        with:
          file_path: 'data.json'
          pr_number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          # personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN}}

      - name: Print file content
        run: echo "${{ steps.retrieve-file.outputs.file_content }}"